# -*- coding: utf-8 -*-
"""preprocessing_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gR8A9LRyvBS5hRrbD6TS6HjtlT404zz-
"""

# preprocessing_person1.py

import pandas as pd


def preprocess_context_data(df: pd.DataFrame):
    """
    Person 1 preprocessing (INDEPENDENT BLOCK)

    Input:
        df -> raw dataframe from dataloader.py

    Returns:
        df_person1 -> cleaned context + pitcher features
    """

    # -------------------------------
    # 1. DEFINE COLUMNS
    # -------------------------------

    context_cols = [
        'Season Number', 'Season Start', 'Season End',
        'Started in', 'Industry'
    ]

    pitcher_cols = [
        'Number of Presenters',
        'Male Presenters', 'Female Presenters',
        'Transgender Presenters', 'Couple Presenters',
        'Pitchers Average Age',
        'Pitchers City', 'Pitchers State'
    ]

    # -------------------------------
    # 2. CLEAN NUMERIC COLUMNS
    # -------------------------------

    num_cols = [
        'Number of Presenters',
        'Male Presenters', 'Female Presenters',
        'Transgender Presenters', 'Couple Presenters',
        'Pitchers Average Age'
    ]

    df[num_cols] = df[num_cols].apply(pd.to_numeric, errors='coerce')
    df[num_cols] = df[num_cols].fillna(df[num_cols].median())

    # -------------------------------
    # 3. CLEAN CATEGORICAL COLUMNS
    # -------------------------------

    cat_cols = ['Industry', 'Pitchers City', 'Pitchers State']

    for col in cat_cols:
        df[col] = df[col].fillna(df[col].mode().iloc[0])

    # -------------------------------
    # 4. FEATURE ENGINEERING
    # -------------------------------

    # Gender diversity (important feature)
    gender_cols = [
        'Male Presenters', 'Female Presenters',
        'Transgender Presenters', 'Couple Presenters'
    ]

    df['team_gender_diversity'] = (
        (df[gender_cols] > 0).sum(axis=1) /
        df['Number of Presenters'].replace(0, 1)
    )

    # Normalize season number
    df['season_number_norm'] = (
        (df['Season Number'] - df['Season Number'].min()) /
        (df['Season Number'].max() - df['Season Number'].min())
    )

    # -------------------------------
    # 5. OUTPUT DATAFRAME
    # -------------------------------

    df_person1 = df[
        context_cols +
        pitcher_cols +
        ['team_gender_diversity', 'season_number_norm']
    ].copy()

    return df_person1

