# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gR8A9LRyvBS5hRrbD6TS6HjtlT404zz-
"""

# preprocessing_person2.py

import pandas as pd


def preprocess_financial_data(df: pd.DataFrame, df_person3: pd.DataFrame):
    """
    Person 2 preprocessing (RUN AFTER PERSON 3)

    Input:
        df -> raw dataframe
        df_person3 -> cleaned shark dataframe (from Person 3)

    Returns:
        df_person2 -> cleaned financial + deal features
        y_reg -> regression target (Total Deal Amount)
        y_cls -> classification target (Accepted Offer)
    """

    # -------------------------------
    # 1. DEFINE COLUMNS
    # -------------------------------

    shark_amt_cols = [
        'Namita Investment Amount', 'Vineeta Investment Amount',
        'Anupam Investment Amount', 'Aman Investment Amount',
        'Peyush Investment Amount', 'Ritesh Investment Amount',
        'Amit Investment Amount'
    ]

    financial_cols = [
        'Yearly Revenue', 'Monthly Sales', 'Gross Margin',
        'Net Margin', 'EBITDA', 'Cash Burn', 'SKUs'
    ]

    ask_cols = [
        'Original Ask Amount', 'Original Offered Equity', 'Valuation Requested'
    ]

    target_cols = ['Accepted Offer']

    # -------------------------------
    # 2. 🔥 RECOMPUTE DEPENDENT COLUMNS
    # -------------------------------

    # NEVER use raw dataset values for these
    df['Total Deal Amount'] = df_person3[shark_amt_cols].sum(axis=1)

    df['Number of Sharks in Deal'] = (
        (df_person3[shark_amt_cols] > 0).sum(axis=1)
    )

    # -------------------------------
    # 3. CLEAN NUMERIC DATA
    # -------------------------------

    num_cols = financial_cols + ask_cols

    # Convert to numeric
    df[num_cols] = df[num_cols].apply(pd.to_numeric, errors='coerce')

    # Median imputation (valid here)
    df[num_cols] = df[num_cols].fillna(df[num_cols].median())

    # -------------------------------
    # 4. CLEAN TARGET COLUMN
    # -------------------------------

    # Ensure binary
    df['Accepted Offer'] = df['Accepted Offer'].fillna(0).astype(int)

    # -------------------------------
    # 5. FEATURE ENGINEERING
    # -------------------------------

    # Avoid division by zero
    df['Original Offered Equity'] = df['Original Offered Equity'].replace(0, 1e-6)
    df['Original Ask Amount'] = df['Original Ask Amount'].replace(0, 1e-6)

    df['ask_per_equity'] = df['Original Ask Amount'] / df['Original Offered Equity']

    df['valuation_ask_ratio'] = df['Valuation Requested'] / df['Original Ask Amount']

    df['revenue_ask_ratio'] = df['Yearly Revenue'] / df['Original Ask Amount']

    df['is_revenue_positive'] = (df['Yearly Revenue'] > 0).astype(int)

    # -------------------------------
    # 6. TARGETS
    # -------------------------------

    y_reg = df['Total Deal Amount']
    y_cls = df['Accepted Offer']

    # -------------------------------
    # 7. OUTPUT DATAFRAME
    # -------------------------------

    df_person2 = df[
        financial_cols +
        ask_cols +
        [
            'ask_per_equity',
            'valuation_ask_ratio',
            'revenue_ask_ratio',
            'is_revenue_positive',
            'Number of Sharks in Deal'
        ]
    ].copy()

    return df_person2, y_reg, y_cls

