# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gR8A9LRyvBS5hRrbD6TS6HjtlT404zz-
"""

# preprocessing_person3.py

import pandas as pd
from dataloader import load_dataset

df = load_dataset()

def preprocess_shark_data(df):
    """
    Person 3 preprocessing (MUST RUN FIRST)

    Input:
        df -> raw dataframe from dataloader.py

    Returns:
        df_person3 -> cleaned shark-related features
        y_shark -> multi-label target (7 sharks)
    """

    # -------------------------------
    # 1. DEFINE COLUMNS
    # -------------------------------

    shark_amt_cols = [
        'Namita Investment Amount', 'Vineeta Investment Amount',
        'Anupam Investment Amount', 'Aman Investment Amount',
        'Peyush Investment Amount', 'Ritesh Investment Amount',
        'Amit Investment Amount'
    ]

    shark_present_cols = [
        'Namita Present', 'Vineeta Present', 'Anupam Present',
        'Aman Present', 'Peyush Present', 'Ritesh Present',
        'Amit Present', 'Guest Present'
    ]

    # -------------------------------
    # 2. CLEANING (CRITICAL RULE)
    # -------------------------------

    # NaN = no investment → 0
    df[shark_amt_cols] = df[shark_amt_cols].fillna(0)

    # NaN = shark not present → 0
    df[shark_present_cols] = df[shark_present_cols].fillna(0)

    # Ensure numeric
    df[shark_amt_cols] = df[shark_amt_cols].apply(pd.to_numeric, errors='coerce').fillna(0)

    # -------------------------------
    # 3. FEATURE ENGINEERING
    # -------------------------------

    # Total sharks present in panel
    df['sharks_present_count'] = df[shark_present_cols].sum(axis=1)

    # -------------------------------
    # 4. TARGET CREATION (OBJECTIVE 3)
    # -------------------------------

    # Multi-label target (binary)
    y_shark = (df[shark_amt_cols] > 0).astype(int)

    # Rename target columns (optional but clean)
    y_shark.columns = [
        'Namita_Invested', 'Vineeta_Invested',
        'Anupam_Invested', 'Aman_Invested',
        'Peyush_Invested', 'Ritesh_Invested',
        'Amit_Invested'
    ]

    # -------------------------------
    # 5. OUTPUT DATAFRAME
    # -------------------------------

    df_person3 = df[
        shark_amt_cols +
        shark_present_cols +
        ['sharks_present_count']
    ].copy()

    return df_person3, y_shark

